name: AWS Connection Check

on:
  push:
    branches:
      - main

jobs:
  aws-check:
    runs-on: ubuntu-latest
    environment: env-for-pipelines

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Test AWS connection
        run: |
          echo "Listing ECR repositories to check connection..."
          aws ecr describe-repositories