name: Build, Test Docker and Deploy to ECR

on:
  push:
    tags:
      - '*'  # parte solo quando viene creato un tag

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: env-for-pipeline

    steps:
      # Step 1: Checkout del codice
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configura AWS CLI
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Login su ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Step 4: Build Docker e test Maven nel Dockerfile
      - name: Build Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: springboot-app
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          # Build immagine Docker
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .

      # Step 5: Test API endpoint nel container runtime
      - name: Test API endpoint
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: springboot-app
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          # Avvia container in background per test API
          docker run -d --name test-container -p 8080:8080 $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          sleep 15  # attendi avvio app

          # Test API endpoint
          echo "Chiamata API /api/codice-fiscale/SCGLCU00P26D773Q..."
          RESPONSE=$(curl --silent http://localhost:8080/api/codice-fiscale/SCGLCU00P26D773Q)
          echo "API response: $RESPONSE"

          # Assert sulla presenza delle chiavi
          if ! echo "$RESPONSE" | grep -q '"data_nascita"'; then
            echo "data_nascita non presente nella risposta"
            docker stop test-container
            docker rm test-container
            exit 1
          fi

          if ! echo "$RESPONSE" | grep -q '"eta"'; then
            echo "eta non presente nella risposta"
            docker stop test-container
            docker rm test-container
            exit 1
          fi

          echo "Test API completato con successo!"
          docker stop test-container
          docker rm test-container

      # Step 6: Push Docker image to ECR
      - name: Push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: springboot-app
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest